title: Jason Chen # your name (or website title) here
logo: "/images/IMG_1043.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer at Commonwealth Computer Research, Inc., Virginia, United States Jun 2021 - Aug 2021
  <br><br>
  Software Engineer at Fortemedia, Taipei, Taiwan Nov 2016 - Mar 2021  
  <br><br>
  Acoustic Engineer at Foxconn, Taipei, Taiwan Aug 2013 - Oct 2016
  <br><br>
  
  <a href="https://www.linkedin.com/in/jason-chen-88a261142/">View My LinkedIn Profile</a> 
  <a href="https://github.com/aawe44">View My GitHub Profile</a> 
  
